extends: "@istanbuljs/nyc-config-typescript"
require: ["ts-node/register"]
extension: [".ts"]
all: true
cache: true
clean: true
babel-cache: true
sourceMap: true
instrument: true
excludeNodeModules: true
check-coverage: true
include: ["src/*.ts", "src/lib/*.ts", "src/cli/*.ts"]
exclude: ["src/**/*.spec.ts", "src/cli/run.ts"]
ignore-class-method: ["render"]
reporter: ["lcov", "html", "text","text-summary"]
report-dir: reports/coverage
branches: 100
lines: 99
functions: 96
statements: 99