version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  ci:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run All Automated tests
          command: npm run test
      - run:
          name: Code Coverage 
          command: npm run report test
      - store_test_results:
          path: test-results         
      - store_artifacts:
          path: test-results

    parallelism: 4

workflows:
  cd:
    jobs:
      - ci

