version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  ci:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run All Automated tests
          command: npm run test
      - run:
          name: Gnerate Report For Test drift-ctl.json
          command: npm run report test
      - run:
          name: Generate Code Coverage Report
          command: npm run coverage
      - run:
          name: List Reports  
          command: ls -als reports/coverage
      - store_test_results:
          path: reports/coverage
      - store_artifacts:
          path: reports/coverage

workflows:
  cd:
    jobs:
      - ci

