version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Code Coverage 
          command: npm run report test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  ci:
    jobs:
      - build_and_test

